version: "2"

services:
  elasticsearch1:
    #entrypoint: /entrypoints/elasticsearch.sh
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    container_name: elasticsearch1
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 5601:5601
      - 9200:9200
    networks:
      - esnet
  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - esdata2:/usr/share/elasticsearch/data
    networks:
      - esnet
  elasticsearch3:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch1"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    mem_limit: 4g
    volumes:
      - esdata3:/usr/share/elasticsearch/data
    networks:
      - esnet
  logstash:
    build: logstash/
    #volumes:
    #  - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    #  - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - 5000:5000
    environment:
      LS_JAVA_OPTS: "-Xmx512m -Xms512m"
    networks:
      - esnet
    depends_on:
      - elasticsearch1
  kibana:
    #image: kibana:latest
    build: kibana/
    container_name: kibana
    #volumes:
    #  - ./kibana/config/:/usr/share/kibana/config
    depends_on:
      - elasticsearch1
    ports:
      - 5601:5601
    networks:
      - esnet

#volumes:
#  esdata1:
#    driver: local
#  esdata2:
#    driver: local
#  esdata3:
#    driver: local
#
#networks:
#  esnet:
