# https://docs.docker.com/v1.7/compose/yml/
#"version": 1

elasticsearch:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
#  command: "elasticsearch -Ecluster.name=search-cluter -Enode.master=true -Enode.data=false"
  environment:
    - cluster.name=search-cluster
    - node.name=master
    - bootstrap.memory_lock=true
    - xpack.security.enabled=false
#    - "http.host=0.0.0.0"
#    - "network.host=0.0.0.0"
    - "transport.host=127.0.0.1"
    - node.master=true
    - node.data=false
#    - "discovery.type=zen"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile: 
      soft: 65536
      hard: 65536
  mem_limit: 3g
  ports:
    - "9200:9200"
    - "9300:9300"
#  links:
#    - kibana:kibana

elasticsearch1:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
#  command: "elasticsearch -Ecluster.name=search-cluster -Ediscovery.zen.ping.unicast.hosts=elasticsearch"
  environment:
    - cluster.name=search-cluster
    - node.name=data1
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - node.master=false
    - node.data=true
    - "network.publish_host=elasticsearch1"
#    - "discovery.zen.ping.multicast.enabled=false"
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
    - "discovery.zen.minimum_master_nodes=1"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile: 
      soft: 65536
      hard: 65536
  mem_limit: 3g
  volumes:
    - /home/elasticsearch/data1:/usr/share/elasticsearch/data
  links:
    - elasticsearch
  expose:
    - "9300"

elasticsearch2:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
#  command: "elasticsearch -Ecluster.name=search-cluster -Ediscovery.zen.ping.unicast.hosts=elasticsearch"
  environment:
    - cluster.name=search-cluster
    - node.name=data2
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - node.master=false
    - node.data=true
    - "network.publish_host=elasticsearch2"
#    - "discovery.zen.ping.multicast.enabled=false"
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
    - "discovery.zen.minimum_master_nodes=1"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile: 
      soft: 65536
      hard: 65536
  mem_limit: 3g
  volumes:
    - /home/elasticsearch/data2:/usr/share/elasticsearch/data
  links:
    - elasticsearch
  expose:
    - "9300"

elasticsearch3:
  image: docker.elastic.co/elasticsearch/elasticsearch:5.5.0
#  command: "elasticsearch -Ecluster.name=search-cluster -Ediscovery.zen.ping.unicast.hosts=elasticsearch"
  environment:
    - cluster.name=search-cluster
    - node.name=data3
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - node.master=false
    - node.data=true
    - "network.publish_host=elasticsearch3"
#    - "discovery.zen.ping.multicast.enabled=false"
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
    - "discovery.zen.minimum_master_nodes=1"
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile: 
      soft: 65536
      hard: 65536
  mem_limit: 3g
  volumes:
    - /home/elasticsearch/data3:/usr/share/elasticsearch/data
  links:
    - elasticsearch
  expose:
    - "9300"

logstash:
  build: logstash/
  #volumes:
  #  - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #  - ./logstash/pipeline:/usr/share/logstash/pipeline
  environment:
    LS_JAVA_OPTS: "-Xmx256m -Xms256m"
  ports:
    - "5000:5000"
    - "5001:5001/udp"
  links:
    - elasticsearch

kibana:
  #image: kibana:latest
  build: kibana/
#  environment:
  #volumes:
  #  - ./kibana/config/:/usr/share/kibana/config
  ports:
    - "5601:5601"
  links:
    - elasticsearch

elastalert:
  image: khezen/elastalert
  links:
    - elasticsearch
  environment:
    ELASTALERT_USER: elastalert
    ELASTALERT_PWD: changeme
    ELASTICSEARCH_HOST: elasticsearch
    ELASTICSEARCH_PORT: 9200

