# https://docs.docker.com/v1.7/compose/yml/
#"version": 1

elasticsearch:
  build: elasticsearch/
  restart: always
  environment:
    - "TZ=Asia/Seoul" # offset +09:00 / DST +09:00
    - cluster.name=search-cluster
    - node.name=node1
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - http.cors.enabled=true
    - http.cors.allow-origin=*
    - http.cors.allow-methods=*
    - http.cors.allow-headers=*
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=false
    - xpack.graph.enabled=false
    - xpack.watcher.enabled=false
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile: 
      soft: 65536
      hard: 65536
  mem_limit: 3g
  volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - /home/elasticsearch/data1:/usr/share/elasticsearch/data
  ports:
    - 9200:9200
  expose:
    - "9300"

elasticsearch2:
  build: elasticsearch/
  restart: always
  environment:
    - "TZ=Asia/Seoul" # offset +09:00 / DST +09:00
    - cluster.name=search-cluster
    - node.name=node2
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=false
    - xpack.graph.enabled=false
    - xpack.watcher.enabled=false
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile: 
      soft: 65536
      hard: 65536
  mem_limit: 3g
  volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - /home/elasticsearch/data2:/usr/share/elasticsearch/data
  links:
    - elasticsearch
  expose:
    - "9300"

elasticsearch3:
  build: elasticsearch/
  restart: always
  environment:
    - "TZ=Asia/Seoul" # offset +09:00 / DST +09:00
    - cluster.name=search-cluster
    - node.name=node3
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - "discovery.zen.ping.unicast.hosts=elasticsearch"
    - xpack.security.enabled=false
    - xpack.monitoring.enabled=false
    - xpack.graph.enabled=false
    - xpack.watcher.enabled=false
  ulimits:
    memlock:
      soft: -1
      hard: -1
    nofile: 
      soft: 65536
      hard: 65536
  mem_limit: 3g
  volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
    - /home/elasticsearch/data3:/usr/share/elasticsearch/data
  links:
    - elasticsearch
  expose:
    - "9300"

logstash:
  build: logstash/
  restart: always
  volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
  #  - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
  #  - ./logstash/pipeline:/usr/share/logstash/pipeline
  environment:
    - "TZ=Asia/Seoul" # offset +09:00 / DST +09:00
    - "LS_JAVA_OPTS=-Xmx1g -Xms1g"
  ports:
    - "5000:5000"
    - "5001:5001/udp"
  links:
    - elasticsearch

kibana:
#  image: docker.elastic.co/kibana/kibana:5.5.0
  build: kibana/
  restart: always
  environment:
    - "TZ=Asia/Seoul" # offset +09:00 / DST +09:00
#    - ELASTICSEARCH_URL=http://elasticsearch:9200
    - XPACK_GRAPH_ENABLED=false
    - XPACK_MONITORING_ENABLED=false
    - XPACK_REPORTING_ENABLED=false
    - XPACK_SECURITY_ENABLED=false
  volumes:
    - "/etc/timezone:/etc/timezone:ro"
    - "/etc/localtime:/etc/localtime:ro"
  #  - ./kibana/config/:/usr/share/kibana/config
  ports:
    - 5601:5601
  links:
    - elasticsearch

